### ISSUE TITLE
/tpall not working for me

### ISSUE THREAD

**Issue by helptiger** [AddstarMC/geSuitTeleport#10]
1. /tpall
2. (in Chat) All players have been teleported to NAME
3. nothing happens

latest bungeecord, all servers on 1.10.2 with protocolsupport

**Comment by addstar** [comment]
Can you please check the server+proxy console and also let me know the exact versions/builds of bungeecord, spigot, geSuit (proxy) + geSuitTeleport. Thanks.

**Comment by helptiger** [comment]
BungeeCord v1204, Spigot is 1.10.2 (16/11/16), also latest Paperspigot 1.10.2, geSuit build 114, geSuitTeleport build 20 and 21
no errors in console, message in chat but no teleportations

**Comment by helptiger** [comment]
here is an error in proxy.log.0
http://pastebin.com/jiuAPQiY

**Comment by helptiger** [comment]
debug /tpall (tpmessage, but no teleport)

[19:51:34] [Server thread/INFO]: fehlfarben issued server command: /tpall
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Checking if WG allows TP. Status of Plugin:true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[/fly]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] World guard check for TP completed: Player=§8§mfarben§r Location=(Location{world=CraftWorld{name=world},x=-47.38863752717708,y=71.0,z=8.393713773835369,pitch=12.2002,yaw=272.351}) Region TP Allowed=true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Checking if WG allows TP. Status of Plugin:true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[/fly]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] World guard check for TP completed: Player=§8§mfarben§r Location=(Location{world=CraftWorld{name=world},x=-47.38863752717708,y=71.0,z=8.393713773835369,pitch=12.2002,yaw=272.351}) Region TP Allowed=true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Checking if WG allows TP. Status of Plugin:true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[/fly]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] World guard check for TP completed: Player=§8§mfarben§r Location=(Location{world=CraftWorld{name=world},x=-47.38863752717708,y=71.0,z=8.393713773835369,pitch=12.2002,yaw=272.351}) Region TP Allowed=true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Checking if WG allows TP. Status of Plugin:true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[/fly]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] World guard check for TP completed: Player=§8§mfarben§r Location=(Location{world=CraftWorld{name=world},x=-47.38863752717708,y=71.0,z=8.393713773835369,pitch=12.2002,yaw=272.351}) Region TP Allowed=true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Checking if WG allows TP. Status of Plugin:true
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[/fly]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Blocked Commands Found:[]
[19:51:35] [Server thread/INFO]: [geSuitTeleports] Tests on List:[] completed
[19:51:35] [Server thread/INFO]: [geSuitTeleports] World guard check for TP completed: Player=§8§mfarben§r Location=(Location{world=CraftWorld{name=world},x=-47.38863752717708,y=71.0,z=8.393713773835369,pitch=12.2002,yaw=272.351}) Region TP Allowed=true

**Comment by helptiger** [comment]
some error in console (related with teleport)
18:43:41 [WARNING] [geSuit] Unable to find player named "ElektronicHD" in onlinePlayers list!
18:43:41 [SEVERE] Dec 18, 2016 6:43:41 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@43b7ff22, receiver=xNichtVorhanden), cancelled=false, tag=geSuitTeleport) to listener net.cubespace.geSuit.listeners.TeleportsMessageListener@118102ee
java.lang.NullPointerException
	at net.cubespace.geSuit.managers.TeleportManager.setPlayersDeathBackLocation(TeleportManager.java:164)
	at net.cubespace.geSuit.listeners.TeleportsMessageListener.receivePluginMessage(TeleportsMessageListener.java:85)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:228)
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:61)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
