### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Serux18** [AddstarMC/geSuitTeleport#5]
[00:02:20] [Server thread/ERROR]: Unhandled exception executing command 'tp' in plugin geSuitTeleports v0.2.0b-MyM-Snapshot
org.bukkit.command.CommandException: Unhandled exception executing command 'tp' in plugin geSuitTeleports v0.2.0b-MyM-Snapshot
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:417) [Essentials-2x.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2x.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.CommandBlockListenerAbstract.executeCommand(CommandBlockListenerAbstract.java:211) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:92) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.BlockCommand.b(BlockCommand.java:48) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:653) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:249) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:769) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6c9b0a1-de5c261]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at net.cubespace.geSuitTeleports.commands.TPCommand.onCommand(TPCommand.java:45) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6c9b0a1-de5c261]
	... 14 more

**Comment by Narimm** [comment]
Basically you are calling /tp from what looks like a commandblock using only 4 params
ie /tp x y z server you will need to use 
/tp playername x y z server 

with only 3 params its
/tp x y z 

keep in mind if the player does not resolve then it will assume that the name is a world name and try that if you specify 5 parameters for the TP
